### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by SleepProgger** [tyt2y3/vaser-unity#1]
Hi, thanks for sharing this code.
But under which license is this published ?

*I tried porting your old version, which is under a BSD license, but tbh, the code is not that easy to understand, and has evolved by quite a bit since your post from 2011.
So, if the license would allow it i would love to port your unity version.*

**Comment by SleepProgger** [comment]
Huh, that was really quick. Thank you very much :)

Btw: if you would write up an article with your findings since 2011 it would for sure find reader.
2d Line rendering is still a tricky subject a lot of engines/render don't get quite right.

**Comment by tyt2y3** [comment]
Hi there. I am just (re) starting this project again and was still deciding on a license. Cheers. Hope you'd find this useful.
And if you have made something great, let me know.

**Comment by SleepProgger** [comment]
Will do. Sorry for trashing this issue, but is the problem with tight corners (line-width > segment length) still existent ?

Also would you mind if i send you a quick mail to talk a bit about this ?

**Comment by tyt2y3** [comment]
Okay
